### ISSUE TITLE
Wrong Commands

### ISSUE THREAD

**Issue by radhasaraf** [rportugal/opencv-zbar#2]
I was using the code zbar_opencv for an application when I realized that in your readme file the following commands: 
$ mkdir build
$ cd build 
$ cmake ..
must be replaced with the following commands:
$ git clone https://github.com/rportugal/opencv-zbar.git
$ cd opencv-zbar
$ cmake .

**Comment by rportugal** [comment]
Both of them work on Mac. Closing.
